language: python
python:
  - "3.6"
install:
  - pip install -r requirements.txt
script:
  - nosetests
deploy:
  - provider: pypi
    user: "$pypitest_user"
    password: "$pypitest_pass"
    server: "https://test.pypi.org/legacy/"
  - provider: pypi
    user: "$pypi_user"
    password: "$pypi_pass"
